//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseEquipmentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLogs
    {
        public long Id { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
        public string ActionType { get; set; }
        public string OldData { get; set; }
        public string NewData { get; set; }
        public int ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
