//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseEquipmentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentPhotos = new HashSet<EquipmentPhotos>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public int TypeId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string Description { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentPhotos> EquipmentPhotos { get; set; }
        public virtual EquipmentStatuses EquipmentStatuses { get; set; }
        public virtual EquipmentTypes EquipmentTypes { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
