//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseEquipmentManager.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentPhotos
    {
        public int Id { get; set; }
        public int EquipmentId { get; set; }
        public string FilePath { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
